
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/cygdrive/c/Users/chris/AppData/Local/JetBrains/CLion2024.1/cygwin_cmake/share/cmake-3.28.1/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: CYGWIN - 3.5.3-1.x86_64 - x86_64
...
